version: '3'

name: larascript

services:
  postgres:
    container_name: postgres
    image: postgres:18-alpine3.21
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: root
      POSTGRES_PASSWORD: example
      LARASCRIPT_DEFAULT_CREDENTIALS: postgres://root:example@localhost:5432/app
    volumes:
      - postgres_data:/var/lib/postgresql/18/docker
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    external: true
    name: larascript